# Generated by Django 4.2.7 on 2023-11-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='pincode',
            new_name='zipcode',
        ),
    ]
